language: go

addons:
  apt:
    packages:
      - snapd

go:
  - "1.12.x"
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - sudo snap install snapcraft --classic
  - go get -u github.com/gobuffalo/packr/v2/packr2
  - GO111MODULE=on go mod download

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - GO111MODULE=on go build ./cmd/cayley
  - packr2 && GO111MODULE=on go test -v ./...

after_success:
  - test -n "$TRAVIS_TAG" && echo "$SNAP_TOKEN" > snap.login && snapcraft login --with snap.login

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux AND $TRAVIS_GO_VERSION =~ ^1\.12
